src/apps/dados/urls.py
from django.urls import path
from .views import home


app_name = 'dados'
urlpatterns = [
    path('', home, name='homepage'),
]

src/urls.py
from django.urls import path, include
from django.contrib import admin


app_name = 'core'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('src.apps.dados.urls', namespace='core')),
]

src/apps/core/models.py
from django.db import models

# Create your models here.

src/apps/dados/models.py
from django.db import models
from .data import LISTA_MESES  # Combobox


class DadoPessoal(models.Model):
    title = models.CharField(max_length=40, verbose_name='Título')
    description = models.TextField(max_length=500, verbose_name='Descrição')
    dia_evento = models.IntegerField(
        verbose_name='Dia da Ocorrência'
    )
    mes_evento = models.PositiveSmallIntegerField(
        default=1,
        choices=LISTA_MESES,
        verbose_name='Mês da Ocorrência',
    )
    ano_evento = models.IntegerField(
        verbose_name='Ano da Ocorrência'
    )

    class Meta:
        ordering = ['title']
        verbose_name = 'Dado Pessoal'
        verbose_name_plural = 'Dados Pessoais'

    def __str__(self):
        return self.title

src/apps/core/views.py
from django.shortcuts import render

# Create your views here.

src/apps/dados/views.py
from django.shortcuts import render
from .models import DadoPessoal

def home(request):
    data = DadoPessoal.objects.all()
    context = {
        'data': data
    }

    return render(request, 'index.html', context)

src/apps/dados/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>

    {% block css %}
        <!-- Tipo de Codificação -->
        <meta charset="UTF-8">
        <meta name="theme-color" content="#333">
        <!-- Meta Responsive Design -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Ícone na Aba -->
        <link rel="icon" href="https://www.itinovare.com.br/site/images/help_icon.png">
        <!-- Até 90 caracteres -->
        <title>{% block title %}{% endblock title %}</title>
        <!-- Até 153 caracteres -->
        <meta name="description" content="Está buscando um bom desenvolvedor em Franca para construir seu website? Então acesse esse portfólio e confira nossos serviços!">
        <!-- Removendo os Prefixos dos Navegadores -->
        <link rel="stylesheet" href={% static 'css/reset.css' %}>
        <!-- Estilos Gerais -->
        <link rel="stylesheet" href={% static 'css/estilos.css' %}>
        <!-- Ícones -->
        <link rel="stylesheet" href={% static 'css/font-icon.css' %}>
        <!-- Menu -->
        <link rel="stylesheet" href={% static 'css/navbar.css' %}>
        <!-- 'The Road so Far' -->
        <link rel="stylesheet" href={% static 'css/about.css' %}>
        <!-- Fonte -->
        <link href='https://fonts.googleapis.com/css?family=Raleway:200,400,800' rel='stylesheet' type='text/css'>
        <!-- jQuery -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% endblock css %}

</head>
<body>

    {% block main %}{% endblock main %}

    <script type="text/javascript">
		function scrollBanner() {
    	  var scrollPos;
    	  var headerText = document.querySelector('.header-parallax hgroup');
    	  scrollPos = window.scrollY;

    	  if (scrollPos <= 600)
    	      headerText.style.opacity = 1 - (scrollPos/600);

    	}

    	window.addEventListener('scroll', scrollBanner);
	</script>
    <script type="text/javascript">
        /*Scroll to top when arrow up clicked BEGIN*/
        $(window).scroll(function() {
            var height = $(window).scrollTop();
            if (height > 200) {
                $('#back2Top').fadeIn();
            } else {
                $('#back2Top').fadeOut();
            }
        });
        $(document).ready(function() {
            $("#back2Top").click(function(event) {
                event.preventDefault();
                $("html, body").animate({ scrollTop: 0 }, "slow");
                return false;
            });

        });
    </script>

    {% block js %}
        <!-- ScrollSpy -->
        <script src={% static 'js/scrollspy.js' %}></script>
        <!-- Navbar Fixed when Scrolling -->
        <script src={% static 'js/navbar.js' %}></script>
        <!-- Particles moving -->
        <script src={% static 'js/particles/TweenLite.min.js' %}></script>
        <script src={% static 'js/particles/EasePack.min.js' %}></script>
        <script src={% static 'js/particles/rAF.js' %}></script>
        <script src={% static 'js/particles/demo-1.js' %}></script>
        <!-- Road so Far -->
        <script src={% static 'js/about_me/jquery.mobile.custom.min.js' %}></script>
        <script src={% static 'js/about_me/main.js' %}></script>

    {% endblock js %}

</body>
</html>

src/apps/dados/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}
{% trans "Rafael Ribeiro || Ao seu Dispor" %}
{% endblock title %}


{% block main %}
    <section class="header-parallax">
        <article>
            <hgroup>
                <h1 class="main-title">Rafael <span class="thin">Ribeiro</span></h1>
                <br><br>
                <h2 class="main-subtitle">{% trans "Desenvolvedor" %}</h2>
            </hgroup>
            <div id="large-header">
                <canvas id="demo-canvas"></canvas>
            </div>
        </article>
        <p class="conjucture">
            <span class="chevron"></span>
            <span class="chevron"></span>
            <span class="chevron"></span>
        </p>
    </section>
    <main>
        <nav id="navbar" class="tabs">
            <ul class="tabs-container">
                <a href="#about" class="scrollspy">
                    <li>{% trans "Trajetória" %}</li>
                    <i data-icon=">" class="icon"></i>
                </a>
                <a href="#three" class="scrollspy">
                    <li>Ipsum</li>
                    <i data-icon="d" class="icon"></i>
                </a>
                <a href="#four" class="scrollspy">
                    <li>{% trans "Solicitar Orçamento" %}</li>
                    <i data-icon="&#xe006;" class="icon"></i>
                </a>
                <span class="tab-slider"></span>
            </ul>
        </nav>


        <section class="about_me" id="about">

            <h1 class="subtitle_sections">{% trans "Trajetória" %}</h1>


            <br>


            <div class="timeline">
                <div class="events-wrapper">

                    <div class="events">
                        <ol>
                            {% for dados in data %}
                                {% if forloop.first %}
                                    <li>
                                        <a href="#0" data-date="{{ dados.dia_evento }}/{{ dados.mes_evento }}/{{ dados.ano_evento }}" class="selected">{{ dados.dia_evento }} {{ dados.get_mes_evento_display|slice:":3" }}</a>
                                    </li>
                                {% else %}
                                    <li>
                                        <a href="#0" data-date="{{ dados.dia_evento }}/{{ dados.mes_evento }}/{{ dados.ano_evento }}">{{ dados.dia_evento }} {{ dados.get_mes_evento_display|slice:":3" }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ol>
                        <span class="filling-line" aria-hidden="true"></span>
                    </div> <!-- .events -->
                </div> <!-- .events-wrapper -->

                <ul class="cd-timeline-navigation">
                    <li>
                        <a href="#0" class="prev inactive">Prev</a>
                    </li>
                    <li>
                        <a href="#0" class="next">Next</a>
                    </li>
                </ul> <!-- .cd-timeline-navigation -->
            </div> <!-- .timeline -->

            <div class="events-content">

                <ol>
                    {% for dados in data %}
                        {% if forloop.first %}
                            <li class="selected" data-date="{{ dados.dia_evento }}/{{ dados.mes_evento }}/{{ dados.ano_evento }}">
                                <h2>{{ dados.title }}</h2>
                                <em>{{ dados.dia_evento }} de {{ dados.get_mes_evento_display }} de {{ dados.ano_evento }}</em>
                                <p>
                                {{ dados.description }}
                                </p>
                            </li>
                            {% else %}
                            <li data-date="{{ dados.dia_evento }}/{{ dados.mes_evento }}/{{ dados.ano_evento }}">
                                <h2>{{ dados.title }}</h2>
                                <em>{{ dados.dia_evento }} de {{ dados.get_mes_evento_display }} de {{ dados.ano_evento }}</em>
                                <p>
                                {{ dados.description }}
                                </p>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ol>
            </div> <!-- .events-content -->
        </section>

        <section class="conhecimentos" id="three">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>

        </section>




        <section class="four" id="four"></section>




        <a id="back2Top" title="Back to top" href="#">
            <i style="font-size: 36px" data-icon="Z" class="icon"></i>
        </a>
    </main>
{% endblock main %}